/* QUANDO APERTAR NO CIFRA DE CÉSAR APARECER O INCREMENTO UTILIZADO NA CIFRA */


/* QUANDO APERTAR EM CODIFICAR/DECODIFICAR MUDA O TEXTO DO BOTÃO */


/* QUANDO DIGITAR O TEXTO APARECE O RESULTADO DA SELEÇÃO NA OUTRA CAIXA DE TEXTO */

